SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO
WHERE (FISH_NAME, LENGTH) IN 
(
    SELECT FISH_NAME, MAX(LENGTH)
    FROM FISH_INFO NATURAL JOIN FISH_NAME_INFO
    GROUP BY FISH_NAME
)
ORDER BY ID;